// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_linked_list`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-07-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `zur1-vm-devleo-001`, CPU: `AMD EPYC 9354 32-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/kitchensink-runtime/kitchensink_runtime.compact.compressed.wasm
// --pallet
// pallet_linked_list
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// substrate/.maintain/frame-umbrella-weight-template.hbs
// --output
// substrate/frame/linked-list/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame::weights_prelude::*;

/// Weight functions needed for `pallet_linked_list`.
pub trait WeightInfo {
	fn insert(s: u32, ) -> Weight;
	fn remove() -> Weight;
	fn re_insert_in_place() -> Weight;
	fn re_insert_relocate(s: u32, ) -> Weight;
	fn reprioritize_no_op() -> Weight;
	fn reprioritize_in_place() -> Weight;
	fn reprioritize_relocate(s: u32, ) -> Weight;
	fn reprioritize_priority_removed() -> Weight;
}

/// Weights for `pallet_linked_list` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `LinkedList::ListNodes` (r:19 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn insert(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247 + s * (38 ±0)`
		//  Estimated: `8577 + s * (2529 ±0)`
		// Minimum execution time: 26_520_000 picoseconds.
		Weight::from_parts(28_276_429, 8577)
			// Standard Error: 7_367
			.saturating_add(Weight::from_parts(6_293_279, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::ListNodes` (r:3 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `8577`
		// Minimum execution time: 25_390_000 picoseconds.
		Weight::from_parts(27_830_000, 8577)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `LinkedList::ListNodes` (r:3 w:1)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn re_insert_in_place() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `8577`
		// Minimum execution time: 19_090_000 picoseconds.
		Weight::from_parts(21_010_000, 8577)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LinkedList::ListNodes` (r:21 w:5)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn re_insert_relocate(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324 + s * (38 ±0)`
		//  Estimated: `13635 + s * (2529 ±0)`
		// Minimum execution time: 49_700_000 picoseconds.
		Weight::from_parts(53_821_395, 13635)
			// Standard Error: 8_006
			.saturating_add(Weight::from_parts(6_321_761, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:1 w:0)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn reprioritize_no_op() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3519`
		// Minimum execution time: 13_181_000 picoseconds.
		Weight::from_parts(14_730_000, 3519)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:3 w:1)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn reprioritize_in_place() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `293`
		//  Estimated: `8577`
		// Minimum execution time: 24_920_000 picoseconds.
		Weight::from_parts(28_360_000, 8577)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:21 w:5)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn reprioritize_relocate(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `389 + s * (38 ±0)`
		//  Estimated: `13635 + s * (2529 ±0)`
		// Minimum execution time: 56_250_000 picoseconds.
		Weight::from_parts(61_456_442, 13635)
			// Standard Error: 8_148
			.saturating_add(Weight::from_parts(6_231_447, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:3 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn reprioritize_priority_removed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `8577`
		// Minimum execution time: 30_600_000 picoseconds.
		Weight::from_parts(33_991_000, 8577)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `LinkedList::ListNodes` (r:19 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn insert(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247 + s * (38 ±0)`
		//  Estimated: `8577 + s * (2529 ±0)`
		// Minimum execution time: 26_520_000 picoseconds.
		Weight::from_parts(28_276_429, 8577)
			// Standard Error: 7_367
			.saturating_add(Weight::from_parts(6_293_279, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::ListNodes` (r:3 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `8577`
		// Minimum execution time: 25_390_000 picoseconds.
		Weight::from_parts(27_830_000, 8577)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `LinkedList::ListNodes` (r:3 w:1)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn re_insert_in_place() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `8577`
		// Minimum execution time: 19_090_000 picoseconds.
		Weight::from_parts(21_010_000, 8577)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `LinkedList::ListNodes` (r:21 w:5)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn re_insert_relocate(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `324 + s * (38 ±0)`
		//  Estimated: `13635 + s * (2529 ±0)`
		// Minimum execution time: 49_700_000 picoseconds.
		Weight::from_parts(53_821_395, 13635)
			// Standard Error: 8_006
			.saturating_add(Weight::from_parts(6_321_761, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:1 w:0)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn reprioritize_no_op() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3519`
		// Minimum execution time: 13_181_000 picoseconds.
		Weight::from_parts(14_730_000, 3519)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:3 w:1)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn reprioritize_in_place() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `293`
		//  Estimated: `8577`
		// Minimum execution time: 24_920_000 picoseconds.
		Weight::from_parts(28_360_000, 8577)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:21 w:5)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[0, 16]`.
	fn reprioritize_relocate(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `389 + s * (38 ±0)`
		//  Estimated: `13635 + s * (2529 ±0)`
		// Minimum execution time: 56_250_000 picoseconds.
		Weight::from_parts(61_456_442, 13635)
			// Standard Error: 8_148
			.saturating_add(Weight::from_parts(6_231_447, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(Weight::from_parts(0, 2529).saturating_mul(s.into()))
	}
	/// Storage: `LinkedList::BenchAuthoritativePriority` (r:1 w:0)
	/// Proof: `LinkedList::BenchAuthoritativePriority` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:3 w:3)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:1 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn reprioritize_priority_removed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249`
		//  Estimated: `8577`
		// Minimum execution time: 30_600_000 picoseconds.
		Weight::from_parts(33_991_000, 8577)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
