[package]
name = "pallet-stability"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME pallet for the stablecoin stability pool."

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, features = ["derive"] }
frame = { workspace = true, features = ["runtime"] }
pusd-primitives = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }

[dev-dependencies]
pallet-assets = { workspace = true, features = ["std"] }
pallet-assets-holder = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
pallet-linked-list = { workspace = true, features = ["std"] }
pallet-redemptions = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
pallet-vaults = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"pallet-assets-holder/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-linked-list/std",
	"pallet-redemptions/std",
	"pallet-timestamp/std",
	"pallet-vaults/std",
	"pusd-primitives/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-assets-holder/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-linked-list/runtime-benchmarks",
	"pallet-redemptions/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-vaults/runtime-benchmarks",
	"pusd-primitives/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-assets-holder/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-linked-list/try-runtime",
	"pallet-redemptions/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-vaults/try-runtime",
	"pusd-primitives/try-runtime",
]
