// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_redemptions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-07-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `zur1-vm-devleo-001`, CPU: `AMD EPYC 9354 32-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// target/release/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/kitchensink-runtime/kitchensink_runtime.compact.compressed.wasm
// --pallet
// pallet_redemptions
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// substrate/.maintain/frame-weight-template.hbs
// --output
// substrate/frame/redemptions/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame::deps::{frame_support, frame_system};
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_redemptions`.
pub trait WeightInfo {
	fn redeem(s: u32, ) -> Weight;
	fn set_redemption_config() -> Weight;
}

/// Weights for `pallet_redemptions` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Vaults::BranchStates` (r:1 w:1)
	/// Proof: `Vaults::BranchStates` (`max_values`: Some(16), `max_size`: Some(369), added: 864, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Values` (r:1 w:0)
	/// Proof: `Oracle::Values` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::BranchConfigs` (r:1 w:0)
	/// Proof: `Vaults::BranchConfigs` (`max_values`: Some(16), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionConfigs` (r:1 w:0)
	/// Proof: `Redemptions::RedemptionConfigs` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionStates` (r:1 w:1)
	/// Proof: `Redemptions::RedemptionStates` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:2 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::Vaults` (r:16 w:16)
	/// Proof: `Vaults::Vaults` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:16 w:16)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:16 w:16)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(553), added: 3028, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:17 w:17)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 16]`.
	fn redeem(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2087 + s * (573 ±0)`
		//  Estimated: `6108 + s * (3028 ±0)`
		// Minimum execution time: 199_970_000 picoseconds.
		Weight::from_parts(77_681_117, 6108)
			// Standard Error: 294_453
			.saturating_add(Weight::from_parts(143_614_241, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 3028).saturating_mul(s.into()))
	}
	/// Storage: `Vaults::BranchStates` (r:1 w:0)
	/// Proof: `Vaults::BranchStates` (`max_values`: Some(16), `max_size`: Some(369), added: 864, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Values` (r:1 w:0)
	/// Proof: `Oracle::Values` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::BranchConfigs` (r:1 w:0)
	/// Proof: `Vaults::BranchConfigs` (`max_values`: Some(16), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionConfigs` (r:0 w:1)
	/// Proof: `Redemptions::RedemptionConfigs` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	fn set_redemption_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1042`
		//  Estimated: `3501`
		// Minimum execution time: 26_230_000 picoseconds.
		Weight::from_parts(30_250_000, 3501)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Vaults::BranchStates` (r:1 w:1)
	/// Proof: `Vaults::BranchStates` (`max_values`: Some(16), `max_size`: Some(369), added: 864, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Values` (r:1 w:0)
	/// Proof: `Oracle::Values` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::BranchConfigs` (r:1 w:0)
	/// Proof: `Vaults::BranchConfigs` (`max_values`: Some(16), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionConfigs` (r:1 w:0)
	/// Proof: `Redemptions::RedemptionConfigs` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionStates` (r:1 w:1)
	/// Proof: `Redemptions::RedemptionStates` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListMetas` (r:2 w:1)
	/// Proof: `LinkedList::ListMetas` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::Vaults` (r:16 w:16)
	/// Proof: `Vaults::Vaults` (`max_values`: None, `max_size`: Some(205), added: 2680, mode: `MaxEncodedLen`)
	/// Storage: `LinkedList::ListNodes` (r:16 w:16)
	/// Proof: `LinkedList::ListNodes` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:16 w:16)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(553), added: 3028, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:17 w:17)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 16]`.
	fn redeem(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2087 + s * (573 ±0)`
		//  Estimated: `6108 + s * (3028 ±0)`
		// Minimum execution time: 199_970_000 picoseconds.
		Weight::from_parts(77_681_117, 6108)
			// Standard Error: 294_453
			.saturating_add(Weight::from_parts(143_614_241, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(s.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((4_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 3028).saturating_mul(s.into()))
	}
	/// Storage: `Vaults::BranchStates` (r:1 w:0)
	/// Proof: `Vaults::BranchStates` (`max_values`: Some(16), `max_size`: Some(369), added: 864, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Values` (r:1 w:0)
	/// Proof: `Oracle::Values` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::BranchConfigs` (r:1 w:0)
	/// Proof: `Vaults::BranchConfigs` (`max_values`: Some(16), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `Redemptions::RedemptionConfigs` (r:0 w:1)
	/// Proof: `Redemptions::RedemptionConfigs` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	fn set_redemption_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1042`
		//  Estimated: `3501`
		// Minimum execution time: 26_230_000 picoseconds.
		Weight::from_parts(30_250_000, 3501)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
